# Generated by Django 4.1.7 on 2023-03-22 21:08

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_column='f.name', max_length=50, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='First name')),
                ('last_name', models.CharField(db_column='l.name', max_length=50, verbose_name='Last name')),
                ('birthday', models.DateField(default=datetime.date(2023, 3, 22))),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(default=None, max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Students',
            },
        ),
    ]
