# Generated by Django 4.1.7 on 2023-02-27 21:00

import datetime
from django.db import migrations, models
import students.validators


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(default=datetime.date(2023, 2, 27)),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, validators=[students.validators.ValidateEmailDomains('gmail.com', 'yahoo.com', 'hotmail.com'), students.validators.validate_unique_email]),
        ),
    ]
