# Generated by Django 4.1.7 on 2023-03-23 00:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(default=datetime.date(2023, 3, 23)),
        ),
    ]
