# Generated by Django 4.1.7 on 2023-02-17 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='Students',
        ),
    ]
