# Generated by Django 4.1.7 on 2023-03-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_phone_alter_student_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
