# Generated by Django 4.1.7 on 2023-04-22 21:01

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import students.validators


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_alter_group_start_date'),
        ('students', '0005_alter_student_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='groups.group'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.date(2023, 4, 22)),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, validators=[students.validators.ValidateEmailDomains('gmail.com', 'yahoo.com', 'hotmail.com'), students.validators.validate_unique_email]),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(db_column='f_name', max_length=50, validators=[django.core.validators.MinLengthValidator(3, message='"First name" field value less than 2 symbols')], verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(db_column='l_name', max_length=50, validators=[django.core.validators.MinLengthValidator(3, message='"Last name" field value less than 2 symbols')], verbose_name='Last name'),
        ),
    ]
