# Generated by Django 4.1.7 on 2023-04-23 00:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_group_alter_student_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.date(2023, 4, 23)),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(default=None, max_length=13),
        ),
    ]
