# Generated by Django 4.1.7 on 2023-03-31 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_teacher_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='birth_date',
            field=models.DateField(default=datetime.date(2023, 3, 31)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(db_column='f_name', max_length=50, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(db_column='l_name', max_length=50, verbose_name='Last name'),
        ),
    ]
