# Generated by Django 4.1.7 on 2023-04-23 20:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0010_group_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(db_column='c.name', max_length=50, verbose_name='Course name')),
                ('start_date', models.DateField(default=datetime.date(2023, 4, 23))),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('course_description', models.TextField()),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='groups.group')),
            ],
            options={
                'db_table': 'Course',
            },
        ),
    ]
