# Generated by Django 4.1.7 on 2023-03-23 00:56

import datetime
from django.db import migrations, models
import groups.validators


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 3, 23), validators=[groups.validators.validate_start_date]),
        ),
    ]
