# Generated by Django 4.1.7 on 2023-04-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_alter_teacher_birth_date'),
        ('groups', '0009_group_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='groups', to='teachers.teacher'),
        ),
    ]
